version: '3.9'
services:
  lova-postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: lova-pgsql
    ports:
      - 5432:5432
    volumes:
      - db_postgresql:/var/lib/postgresql/data
volumes:
  db_postgresql:
